name: Terraform deployment on Azure
run-name: azure
on:
  push:
    branches: 
      - test
      - main
permissions:
  id-token: write
  contents: write
  actions: write
  checks: write
  deployments: write
  discussions: write
  issues: write
  pages: read
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
jobs:
  terraform_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: test  # Replace with the name of the branch you want to create a PR from
          base: main
          title: merge changes
          body: |
            ## Description
            merging changes from test to main
          token: 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



