name: Terraform deployment on azure
run-name: azure
on:
  push:
    branches: [ test ]
permissions:
  id-token: write
  contents: write
  actions: write
  checks: write
  deployments: write
  discussions: write
  issues: write
  pages: read
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
jobs:
  terraform_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: create pull request for terraform plan approval
        uses: peter-evans/create-pull-request@v3
        with:
          branch: test
          base: main
          title: "terraform plan for approval"
          body: "review this terraform plan"
          reviewers: docdoom12345

