name: Terraform deployment on Azure
run-name: azure
on:
  push:
    branches: [ test ]
permissions:
  id-token: write
  contents: write
  actions: write
  checks: write
  deployments: write
  discussions: write
  issues: write
  pages: read
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
jobs:
  terraform_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        run: |
          gh pr create --base main --head test --title "Feature XYZ" --body "This pull request includes the following changes: ..."
        env:
          GITHUB_TOKEN: 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



