name: Terraform deployment on Azure
run-name: azure
on:
  push:
    branches: 
      - main
permissions:
  id-token: write
  contents: write
  actions: write
  checks: write
  deployments: write
  discussions: write
  issues: write
  pages: read
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
jobs:
  terraform_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.3
      - name: login to azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: terraform init
        run: terraform init
      - name: terraform plan
        run: terraform plan
        
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
          
      - name: Run Terratest
        run: |
          cd test/
          go mod init github.com/docdoom12345/workflow-terraform
          go test ./test -v
