name: Terraform deployment on azure
run-name: azure
on:
  push:
    branches: [ main ]
jobs:
  terraform_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.3
      - name: login to azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: terraform init
        run: terraform init
      - name: terraform plan
        run: terraform plan
      - name: create pull request for terraform plan approval
        uses: peter-evans/create-pull-request@v3
        with:
          branch: test
          title: "terraform plan for approval"
          body: "review this terraform plan"
          commit-message: "terraform plan for approval"
          labels: "terraform-plan"
          reviewers: docdoom12345
