name: Terraform deployment on Azure
run-name: azure
on:
  push:
    branches: 
      - test
      - main
permissions:
  id-token: write
  contents: write
  actions: write
  checks: write
  deployments: write
  discussions: write
  issues: write
  pages: read
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
jobs:
  terraform_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          # Install GitHub CLI
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Authenticate with GitHub CLI
        run: |
          # Configure GitHub CLI with a Personal Access Token (PAT)
          # Replace 'YOUR_PAT_HERE' with your actual PAT.
          gh auth login --with-token <<< ${{ secrets.PAT_TOKEN }}

      - name: Create Pull Request
        run: |
          # Use the GitHub CLI to create the pull request
          # Replace 'base-branch' and 'feature-branch' with the actual branch names.
          gh pr create --base main --head test --title "merge changes" --body "merge changes from test to main"
